//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 TSCtrlSys.rc 使用
//
#define IDOK2                           2
#define IDCANCEL2                       3
#define IDOK3                           3
#define ID_APP                          3
#define IDC_DLG_PIXEL_BTN_PAT_EDIT      3
#define IDC_BTN_EDIT                    3
#define IDC_Save                        3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDP_SOCKETS_INIT_FAILED         102
#define IDS_COMMAND_LIST                103
#define IDD_DLG_TITLE                   103
#define IDR_POPUP_EDIT                  104
#define IDR_POPUP_EDIT_CN               104
#define IDR_OUTPUT_POPUP_CN             105
#define IDS_TOOL_SETTINGS               106
#define IDS_TOOL_LIVE                   107
#define IDD_PROPPAGE_LARGE              107
#define IDD_PAGE_COMPORT                107
#define IDS_TOOL_STOPLIVE               108
#define IDS_TOOL_MARK                   109
#define IDS_TOOL_OFFSET                 110
#define IDS_TOOL_PIXEL                  111
#define IDS_TOOL_RUN                    112
#define IDS_TOOL_PAUSE                  113
#define IDS_TOOL_STOPRUN                114
#define IDS_TOOL_STEP                   115
#define IDS_TOOL_PARAM                  116
#define IDS_TOOL_REFPOS                 117
#define IDS_TOOL_HOME                   118
#define IDS_TOOL_FEEDHOME               119
#define IDS_TOOL_IO                     120
#define IDS_TOOL_WASH                   121
#define IDS_TOOL_DISPSET                122
#define IDS_TOOL_DOT                    123
#define IDS_TOOL_START                  124
#define IDS_TOOL_PASS                   125
#define IDS_TOOL_ARC                    126
#define IDS_TOOL_END                    127
#define IDS_TOOL_CIRCLE                 128
#define IDS_TOOL_RECT                   129
#define IDS_TOOL_FILL                   130
#define IDS_TOOL_ZHEIGHT                131
#define IDS_TOOL_COATDOT                132
#define IDS_TOOL_COATLINE               133
#define IDS_TOOLS_BDROP                 134
#define IDS_TOOLS_BLINE                 135
#define IDS_TOOL_LISTEDIT               136
#define IDS_TOOL_CHIPAGE                138
#define IDS_APP_STATUS                  140
#define IDS_CMD_COUNT                   141
#define IDS_RUN_STATUS                  142
#define IDS_RUN_COUNT                   143
#define IDS_CUR_CLOCK                   144
#define IDS_CYCLE_TIME                  145
#define IDS_COMPILE_NO                  146
#define IDS_ONLINE_MODE                 147
#define IDS_TOOL_STATUS                 148
#define IDS_TOOL_VER                    149
#define IDS_TOOLBAR_STANDARD            150
#define IDS_TOOLBAR_CUSTOMIZE           151
#define IDR_MAINFRAME                   152
#define IDR_MAINFRAME_256               153
#define IDR_TSCtrlSysTYPE               154
#define ID_VIEW_CUSTOMIZE               155
#define ID_VIEW_OUTPUTWND               156
#define ID_VIEW_PROPERTIESWND           157
#define IDI_OUTPUT_WND                  162
#define IDI_OUTPUT_WND_HC               163
#define IDI_PROPERTIES_WND              164
#define IDI_PROPERTIES_WND_HC           165
#define IDS_OUTPUT_WND                  166
#define IDS_PROPERTIES_WND              167
#define ID_VIEW_NAVIGATION              170
#define IDB_BITMAP_ESTOP                178
#define IDB_BITMAP_PAUSE                179
#define IDB_BITMAP_RUN                  180
#define IDB_BITMAP_STOP                 181
#define IDB_BITMAP_SMILE                182
#define IDR_THEME_MENU                  183
#define IDB_BITMAP_IOSTS                184
#define IDB_BITMAP_COMMAND              185
#define ID_VIEW_APPLOOK_WIN_2000        211
#define ID_VIEW_APPLOOK_OFF_XP          212
#define ID_VIEW_APPLOOK_WIN_XP          213
#define ID_VIEW_APPLOOK_OFF_2003        214
#define ID_VIEW_APPLOOK_VS_2005         215
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   216
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  217
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 218
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   219
#define IDS_MYCALENDARS                 240
#define IDS_CALENDAR                    241
#define IDS_SHORTCUTS                   242
#define IDS_FOLDERS                     243
#define IDS_OUTLOOKBAR                  244
#define IDS_BUILD_TAB                   245
#define IDS_DEBUG_TAB                   246
#define IDS_FIND_TAB                    247
#define IDS_EDIT_MENU                   248
#define IDB_BITMAP_BUTTON               249
#define IDB_BITMAP_MOVE                 250
#define IDB_BITMAP_TOOLBAR              251
#define IDR_MENU_CMD                    252
#define IDR_MENU_CMD_EN                 252
#define IDR_MAINFRAME_COMMAND           253
#define IDR_MENU_CMD_INSERT             254
#define IDR_MENU_CMD_INSERT_EN          254
#define IDR_MENU_CMD_INSERT_PARAM       255
#define IDR_MENU_CMD_INSERT_PARAM_CN    255
#define IDI_LED_OFF                     256
#define IDR_MENU_CMD_CN                 256
#define IDI_LED_ON                      257
#define IDR_MENU_CMD_INSERT_CN          257
#define IDR_MENU_CMD_INSERT_PARAM_EN    258
#define IDR_OUTPUT_POPUP_EN             259
#define IDI_ICON_NET                    260
#define IDR_POPUP_EDIT1                 260
#define IDR_POPUP_EDIT_EN               260
#define IDI_ICON_UNNET                  261
#define IDD_PAGE_IN                     268
#define IDD_PAGE_OUT                    269
#define IDD_PAGE_POS                    270
#define IDD_PAGE_JET                    271
#define IDD_PAGE_SYS                    272
#define IDD_PAGE_APP                    273
#define IDD_PAGE_IMG                    274
#define IDD_DLG_INFO                    304
#define IDD_DLG_MDI                     305
#define IDD_DLG_SHOTCUT                 306
#define IDD_DLG_MARK                    307
#define IDD_DLG_AXISPOS                 308
#define IDD_DLG_STEP                    309
#define IDD_DLG_REPEAT                  310
#define IDD_DLG_SPEED                   311
#define IDD_DLG_NOTE                    312
#define IDD_DLG_GOSUB                   313
#define IDD_DLG_LOOP                    314
#define IDD_DLG_SETIO                   316
#define IDD_DLG_LINE_PARAM              317
#define IDD_DLG_LINE_END                318
#define IDD_DLG_POINT_DISPENSE          319
#define IDD_DLG_POINT_PARAM             320
#define IDD_DLG_NEEDLE_ADJUST           321
#define IDD_DLG_DELAY                   322
#define IDD_DLG_CIRCLE                  324
#define IDD_DLG_GOTO                    325
#define IDD_DLG_LOGIN                   326
#define IDD_DLG_IOCTRL                  327
#define IDD_DLG_DISPENSER               328
#define IDD_DLG_PROG_OFFSET             330
#define IDD_DLG_ZSAME                   331
#define IDD_DLG_ZUPLIMIT1               332
#define IDD_DLG_ZCLEARANCE              333
#define IDD_DLG_POINT_END               334
#define IDD_DLG_SYNC_CONFIG             337
#define IDD_DLG_STANDBY                 340
#define IDD_DLG_ZHEIGHT                 343
#define IDD_DLG_JET_ADJUST              344
#define IDD_DLG_NEEDLE                  372
#define IDD_DLG_JOG_XYZ                 374
#define IDD_DLG_NEEDLE_ZH               375
#define IDD_DLG_TOOL                    376
#define IDD_DLG_JET_PARAM               377
#define IDD_DLG_PIXEL                   378
#define IDD_DLG_ZSET                    379
#define IDD_DLG_REPEAT_ZMETER           380
#define IDD_PAGE_MOTOR                  382
#define IDD_DLG_JOG_FEED                383
#define IDD_DLG_JOG_UNFEED              384
#define IDD_DLG_DISPPARAM               386
#define IDD_DLG_WCL                     387
#define IDD_DLG_WCL1                    388
#define IDD_DLG_WCPOT                   388
#define IDD_DLG_WCRECT                  389
#define IDD_DLG_USERGEGEDIT             390
#define IDD_DLG_PROG_SEL                391
#define IDD_DIALOG1                     392
#define IDD_DLG_TRACK                   392
#define IDD_DLG_LIN_XYZ                 394
#define IDI_ICON_CANCEL                 394
#define IDD_DLG_HPOINT_START            395
#define IDI_ICON3                       395
#define IDI_ICON_OK                     395
#define IDD_DLG_HPOINT_POINT            396
#define IDD_DLG_HPOINT_START2           397
#define IDD_DLG_HPOINT_END              397
#define IDD_DLG_BOARDCALIBEX            398
#define IDD_DLG_BOARDCALIBEX1           399
#define IDD_DLG_BOARDCALIB              399
#define IDD_DLG_FEED_CTRL               400
#define IDD_DLG_INFO_ZBASESET           401
#define IDD_PAGE_BATET_BSW              402
#define IDD_DIALOG2                     403
#define IDD_DLG_EDIT                    403
#define IDI_ICON_EDIT_ARC               404
#define IDI_ICON_EDIT_DOT               405
#define IDI_ICON_EDIT_END               406
#define IDI_ICON_EDIT_PASS              407
#define IDI_ICON_EDIT_START             408
#define IDD_DLG_TRACKDRAW               409
#define IDR_MENU_NEW                    410
#define IDD_DLG_MOVE                    411
#define IDC_CURSOR2                     413
#define IDC_CURSOR_US                   413
#define IDC_CURSOR_UM                   415
#define IDC_CURSOR_UF                   418
#define IDC_CURSOR_DM                   419
#define IDC_CURSOR_DF                   420
#define IDC_CURSOR_DS                   421
#define IDC_CURSOR_LF                   422
#define IDC_CURSOR_LM                   423
#define IDC_CURSOR_LS                   424
#define IDC_CURSOR_RS                   425
#define IDC_CURSOR_RM                   426
#define IDC_CURSOR_RF                   427
#define IDB_BITMAP1                     428
#define IDB_BMP_LOG                     428
#define IDI_ICON_SHUTDOWN               431
#define IDI_ICON_SET                    432
#define IDI_ICON1                       433
#define IDI_ICON_PATH                   433
#define IDI_ICON_USER                   434
#define IDI_ICON_CAMERA                 435
#define IDI_ICON_ALL_ADJUST             437
#define IDI_ICON_SINGLE_ADJUST          438
#define IDI_ICON_SAVE_S                 439
#define IDD_DLG_MACHINE_SET             440
#define IDD_DLG_MACHINE_PARAM           441
#define IDI_ICON_EZ_RUN                 442
#define IDI_ICON_EZ_PAUSE               443
#define IDI_ICON_EZ_STOP                444
#define IDD_DLG_LD_ULD                  445
#define IDI_ICON_ARROW_D                446
#define IDI_ICON2                       447
#define IDI_ICON_ARROW_U                447
#define IDR_MENU1                       448
#define IDR_MENU_NEW_NEEDLE             448
#define IDR_MENU2                       449
#define IDI_ICON4                       450
#define IDI_ICON_MOVETO                 450
#define IDI_ICON5                       451
#define IDI_ICON_HOME                   451
#define IDD_DLG_HPOINT_DOT              452
#define IDD_DLG_DUAL_VALVE              453
#define IDD_DLG_PARAM_LINE              454
#define IDD_DLG_PARAM_DOT               455
#define IDC_DLG_IO_TAB                  480
#define IDC_DLG_IO_IN_GRID              481
#define IDC_DLG_IO_OUT_GRID             482
#define IDC_DLG_IO_IN_GRID2             482
#define IDC_DLG_IO_OUT_OPEN             483
#define IDC_DLG_IO_OUT_CLOSE            484
#define IDC_DLG_IO_OUT_JET              485
#define IDC_DLG_IO_IN_GRID3             486
#define IDC_DLG_IO_OUT_GRID2            486
#define IDC_BUTTON_EDIT0                1000
#define IDC_BUTTON_EDIT1                1001
#define IDC_BUTTON_EDIT2                1002
#define IDC_BUTTON_EDIT3                1003
#define IDC_BUTTON_EDIT4                1004
#define IDC_BUTTON_EDIT5                1005
#define IDC_BUTTON_EDIT6                1006
#define IDC_BUTTON_EDIT7                1007
#define IDC_BUTTON_EDIT8                1008
#define IDC_PAGE_SYS_COMBO_AXIS         1009
#define IDC_PAGE_SYS_EDIT_AXIS_SCALE    1010
#define IDC_PAGE_SYS_EDIT_MAXPOS        1011
#define IDC_PAGE_SYS_EDIT_MINPOS        1012
#define IDC_PAGE_SYS_EDIT_ACC           1013
#define IDC_PAGE_SYS_RADIO1             1014
#define IDC_PAGE_SYS_RADIO2             1015
#define IDC_PAGE_SYS_CHECK_XDIR         1016
#define IDC_PAGE_SYS_CHECK_YDIR         1017
#define IDC_PAGE_SYS_MOVETO_EDIT_VELU   1018
#define IDC_PAGE_SYS_MOVETO_EDIT_VELXY  1019
#define IDC_PAGE_SYS_MOVETO_EDIT_VELZ   1020
#define IDC_PAGE_SYS_JOG_MAX_VELXY      1021
#define IDC_PAGE_SYS_JOG_MAX_VELZ       1022
#define IDC_PAGE_SYS_JOG_MAX_VELU       1023
#define IDC_PAGE_SYS_MOVETO_EDIT_VELV   1024
#define IDC_PAGE_SYS_JOG_MAX_VELV       1025
#define IDC_PAGE_SYS_MOVETO_EDIT_VELM   1026
#define IDC_PAGE_SYS_JOG_MAX_VELM       1027
#define IDC_PAGE_SYS_EDIT_KP            1028
#define IDC_PAGE_SYS_EDIT_KI            1029
#define IDC_COMBO_MARK                  1030
#define IDC_PAGE_SYS_KD                 1030
#define IDC_PAGE_SYS_EDIT_KD            1030
#define IDC_PAGE_SYS_EDIT_KVFF          1031
#define IDC_COMBO_MARK2                 1031
#define IDC_COMBO_MARKMODEID            1031
#define IDC_PAGE_SYS_EDIT_KAFF          1032
#define IDC_PAGE_SYS_EDIT_KD2           1033
#define IDC_PAGE_SYS_EDIT_PVF           1033
#define IDC_MARK_EDIT_ACCEPTANCE        1035
#define IDC_MARK_EDIT_X                 1037
#define IDC_MARK_EDIT_Y                 1038
#define IDC_MARK_EDIT_Z                 1039
#define IDC_DLG_PIXEL_EDIT_RATE         1040
#define IDC_MARK_EDIT_Z2                1040
#define IDC_MARK_EDIT_BZ2               1040
#define IDC_MARK_EDIT_BA                1040
#define IDC_DLG_PIXEL_EDIT_ANG          1041
#define IDC_MARK_EDIT_BA2               1041
#define IDC_JOG_BUTTON_MV6              1042
#define IDC_JOG_BUTTON_MV7              1043
#define IDC_JOG_BUTTON_MV10             1044
#define IDC_JOG_BUTTON_MV11             1045
#define IDC_JOG_BUTTON_MV12             1046
#define IDC_JOG_BUTTON_MV13             1047
#define IDC_JOG_BUTTON_MV14             1048
#define IDC_JOG_BUTTON_MV15             1049
#define IDC_JOG_BUTTON_MV16             1050
#define IDC_JOG_BUTTON_MV17             1051
#define IDC_JOG_CHECK_STEP              1052
#define IDC_JOG_BUTTON_MV18             1053
#define IDC_JOG_BUTTON_V                1053
#define IDC_TESTDISP                    1053
#define IDC_JOG_BUTTON_MV19             1054
#define IDC_JOG_EDIT_STEP_LENGTH        1056
#define IDC_SHOTCUT_JOG_SLIDER_SPEED    1058
#define IDC_STATIC_VERSION              1070
#define IDC_ZSAME_EDIT_TYPE             1071
#define IDC_ZSAME_EDIT_ZHIGH            1072
#define IDC_CIRCLE_COMBO_ITEM           1073
#define IDC_CIRCLE_EDIT_DIAMETER        1074
#define IDC_CIRCLE_RADIO1               1075
#define IDC_CIRCLE_RADIO2               1076
#define IDC_CIRCLE_RADIO_HEAD           1077
#define IDC_CIRCLE_CHECK_DISPENSE_ONOFF 1078
#define IDC_CIRCLE_EDIT_X               1081
#define IDC_CIRCLE_EDIT_Y               1082
#define IDC_CIRCLE_EDIT_Z               1083
#define IDC_CIRCLE_EDIT_U               1084
#define IDC_CIRCLE_EDIT_WEIGHT          1084
#define IDC_REPEAT_EDIT_INDEX           1090
#define IDC_REPEAT_EDIT_XNUM            1091
#define IDC_REPEAT_EDIT_YNUM            1092
#define IDC_REPEAT_EDIT_XSPACE          1093
#define IDC_REPEAT_EDIT_YSPACE          1094
#define IDC_REPEAT_EDIT_TYPE            1095
#define IDC_REPEAT_RADIO1               1096
#define IDC_REPEAT_RADIO2               1097
#define IDC_REPEAT_STATIC_NOTE          1098
#define IDC_REPEAT_EDIT_INDEX2          1098
#define IDC_REPEAT_BTN_EXPAND           1099
#define IDC_REPEAT_EDIT_REPARC          1100
#define IDC_EDIT_XS                     1101
#define IDC_REPEAT_EDIT_YNUM2           1102
#define IDC_EDIT_YS                     1102
#define IDC_PROG_EDIT_STARTINDEX        1105
#define IDC_PROG_EDIT_ENDINDEX          1106
#define IDC_PROG_EDIT_X_MDI_OFFSET      1107
#define IDC_PROG_EDIT_Y_MDI_OFFSET      1108
#define IDC_PROG_EDIT_Z_MDI_OFFSET      1109
#define IDC_OPER_RADIO_HEAD             1111
#define IDC_OPER_CHECK_DISPENSE_ONOFF   1113
#define IDC_EDIT_NOTE                   1140
#define IDC_BTN_READ_AXISPOS            1141
#define IDC_BTN_MOVE                    1142
#define IDC_BTN_APPLY                   1143
#define IDC_BTN_MOVE2                   1143
#define IDC_BTN_MOVE_CALCA              1143
#define IDC_BTN_MOVE_CALCA11111         1143
#define IDC_ZHEIGHT_SAVE                1144
#define IDC_ZHEIGHT_APPLY               1145
#define IDC_INFO_EDIT1                  1155
#define IDC_INFO_EDIT2                  1156
#define IDC_INFO_EDIT3                  1157
#define IDC_INFO_EDIT4                  1158
#define IDC_INFO_EDIT_WASTEGLUE         1158
#define IDC_INFO_EDIT5                  1159
#define IDC_INFO_EDIT6                  1160
#define IDC_INFO_EDIT7                  1161
#define IDC_INFO_EDIT8                  1162
#define IDC_INFO_STATIC_ONLINE          1163
#define IDC_INFO_STATIC_STARTTIME       1164
#define IDC_INFO_STATIC_CYCLETIME       1165
#define IDC_INFO_STATIC_RUNTIME         1166
#define IDC_INFO_STATIC_PRODUCTION      1167
#define IDC_INFO_STATIC_MOTION          1168
#define IDC_INFO_STATIC_BOXNUM          1169
#define IDC_INFO_STATIC_BCDATA          1169
#define IDC_INFO_STATIC_LOAD            1169
#define IDC_INFO_STATIC_BCID            1170
#define IDC_INFO_STATIC_LOAD2           1170
#define IDC_INFO_STATIC_UNLOAD          1170
#define IDC_INFO_STATIC_BCDATA2         1171
#define IDC_INFO_STATIC_BCID2           1172
#define IDC_GOTO_STATIC_NO              1193
#define IDC_GOTO_STATIC_LAB             1194
#define IDC_GOTO_RADIO1                 1195
#define IDC_GOTO_RADIO2                 1196
#define IDC_GOTO_EDIT_START_CMD         1197
#define IDC_GOTO_COMBO_LABEL            1198
#define IDC_PAGE_SYS_BELT_VEL           1220
#define IDC_PAGE_SYS_LOCA_VELXY         1221
#define IDC_PAGE_SYS_VELXY              1222
#define IDC_PAGE_SYS_FEED_UPVEL         1222
#define IDC_PAGE_SYS_LOCA_VELZ          1223
#define IDC_PAGE_SYS_VELZ               1224
#define IDC_PAGE_SYS_FEED_DOWNVEL       1224
#define IDC_PAGE_SYS_HOME_VEL           1225
#define IDC_PAGE_SYS_BELT_VEL2          1225
#define IDC_PAGE_SYS_BELT_UNLOADDELAY   1225
#define IDC_PAGE_SYS_HOME_VELH1         1226
#define IDC_PAGE_SYS_DISP_VEL           1227
#define IDC_PAGE_SYS_HOME_VELL          1228
#define IDC_PAGE_SYS_HOME_VELH2         1229
#define IDC_PAGE_SYS_VELV               1230
#define IDC_PAGE_SYS_VELM               1231
#define IDC_PAGE_SYS_HOME_VELH          1232
#define IDC_PAGE_SYS_FEEDHOME_VELH      1232
#define IDC_PAGE_SYS_HOME_VELM          1233
#define IDC_PAGE_SYS_FEEDHOME_VELM      1233
#define IDC_PAGE_SYS_HOME_VELFEED3      1234
#define IDC_PAGE_SYS_HOME_VELLL         1234
#define IDC_PAGE_SYS_FEEDHOME_VELLL     1234
#define IDC_PAGE_SYS_DISP_VEL2          1235
#define IDC_PAGE_SYS_LOOK_ACC           1235
#define IDC_DLG_NEEDLE_ADJUST_COMBO     1235
#define IDC_DLG_NEEDLE_ADJUST_EDIT_X    1236
#define IDC_DLG_NEEDLE_ADJUST_EDIT_Y    1237
#define IDC_DLG_NEEDLE_ADJUST_EDIT_Z    1238
#define IDC_DLG_NEEDLE_ADJUST_DELTAH    1239
#define IDC_DLG_NEEDLE_ADJUST_DISPTIME  1240
#define IDC_DLG_NEEDLE_ADJUST_OFFTIME   1241
#define IDC_DELAY_EDIT_TYPE             1271
#define IDC_DELAY_EDIT                  1272
#define IDC_GOSUB_EDIT_TYPE             1280
#define IDC_GOSUB_EDIT1                 1281
#define IDC_GOSUB_EDIT2                 1282
#define IDC_GOSUB_EDIT3                 1283
#define IDC_GOSUB_EDIT4                 1284
#define IDC_GOSUB_XDIRDISOFFSET         1284
#define IDC_GOSUB_COMBO_LABEL           1285
#define IDC_GOSUB_YDIRDISOFFSET2        1286
#define IDC_GOSUB_YDIRDISOFFSET         1286
#define IDC_LINE_END_EDIT1              1287
#define IDC_LINE_END_EDIT2              1288
#define IDC_LINE_END_EDIT3              1289
#define IDC_LINE_END_RADIO1             1290
#define IDC_LINE_END_RADIO2             1291
#define IDC_LINE_END_RADIO3             1292
#define IDC_LINE_END_RADIO4             1293
#define IDC_LINE_END_RADIO5             1294
#define IDC_LINE_PARAM_EDIT1            1295
#define IDC_LINE_PARAM_EDIT2            1296
#define IDC_LINE_PARAM_EDIT3            1297
#define IDC_LINE_PARAM_EDIT4            1298
#define IDC_LINE_PARAM_EDIT5            1299
#define IDC_LINE_PARAM_EDIT6            1300
#define IDC_ACCESS_EDIT1                1302
#define IDC_ACCESS_EDIT2                1303
#define IDC_POINT_PARAM_EDIT1           1306
#define IDC_POINT_PARAM_EDIT2           1307
#define IDC_POINT_PARAM_EDIT3           1308
#define IDC_POINT_PARAM_EDIT4           1309
#define IDC_POINT_PARAM_EDIT5           1310
#define IDC_POINT_PARAM_EDIT6           1311
#define IDC_POINT_PARAM_EDIT7           1312
#define IDC_POINT_PARAM_EDIT8           1313
#define IDC_JET_PARAM_OPEN_TIME         1314
#define IDC_JET_PARAM_CLOSE_TIME        1315
#define IDC_SPEED_EDIT_TYPE             1318
#define IDC_SPEED_RADIO1                1319
#define IDC_SPEED_RADIO2                1320
#define IDC_SPEED_RADIO3                1321
#define IDC_SPEED_EDIT_VEL              1322
#define IDC_SPEED_EDIT_VEL2             1323
#define IDC_LOOP_EDIT_STARTINDEX        1324
#define IDC_SPEED_EDIT_VEL3             1324
#define IDC_LOOP_EDIT_LOOPNUM           1325
#define IDC_SPEED_EDIT_VEL4             1325
#define IDC_BUTTON_LEARN                1350
#define IDC_BUTTON_CAL                  1351
#define IDC_BUTTON_CENTER               1352
#define IDC_BUTTON_TEST                 1353
#define IDC_BUTTON_PAT_TEST             1354
#define IDC_DLG_PIXEL_BTN_CALI          1355
#define IDC_STATIC_MARK_PAT             1356
#define IDC_STATIC_PIXEL_PAT            1357
#define IDC_PAGE_IMG_PIXEL_VALUEX       1358
#define IDC_PAGE_IMG_PIXEL_VALUEY       1359
#define IDC_PAGE_IMG_STATIC_PIXEL       1360
#define IDC_STATIC_WAIT                 1371
#define IDC_STATIC_VEL                  1372
#define IDC_STATIC_STS                  1374
#define IDC_STATIC_NO                   1375
#define IDC_STATIC_IN                   1376
#define IDC_STATIC_OUT                  1377
#define IDC_STATIC_ANGLE                1378
#define IDC_STATIC_ANGLERADIUS          1379
#define IDC_MAP_EDIT_OUTPUT             1380
#define IDC_MAP_EDIT_INPUT              1381
#define IDC_RADIO_TYPEINPUT             1390
#define IDC_RADIO_TYPEOUTPUT            1391
#define IDC_IO_RADIO_0                  1392
#define IDC_IO_RADIO_1                  1393
#define IDC_IO_EDIT_NO                  1394
#define IDC_RADIO_TYPE_DELTA_HEIGHT     1395
#define IDC_RADIO_TYPE_ABS_HEIGHT       1396
#define IDC_EDIT_ZCLEARANCE             1397
#define IDC_BUTTON_PWD                  1398
#define IDC_GOSUB_STATIC_X              1400
#define IDC_GOSUB_STATIC_Y              1401
#define IDC_GOSUB_STATIC_Z              1402
#define IDC_GOSUB_STATIC_U              1403
#define IDC_GOSUB_STATIC_Z2             1403
#define IDC_SPEED_STATIC_X              1404
#define IDC_GOSUB_STATIC_Z3             1404
#define IDC_SPEED_STATIC_Y              1405
#define IDC_SPEED_STATIC_Z              1406
#define IDC_SPEED_STATIC_U              1407
#define IDC_SPEED_STATIC_Z2             1407
#define IDC_EDIT_POINT_END_LEN          1410
#define IDC_EDIT_POINT_END1             1411
#define IDC_EDIT_POINT_END2             1412
#define IDC_AXIS_POS_STATIC_U2          1413
#define IDC_CIRCLE_STATIC_U             1416
#define IDC_SYSTEM_STATIC_U             1417
#define IDC_SHOTCUT_STATIC_R            1418
#define IDC_INFO_STATIC_U               1419
#define S8                              1419
#define IDC_INFO_STATIC_U2              1420
#define IDC_INFO_STATIC_V               1420
#define S3                              1420
#define S10                             1420
#define IDC_INFO_STATIC_W               1421
#define S5                              1421
#define IDC_INFO_STATIC_M               1422
#define S7                              1422
#define IDC_INFO_STATIC_N               1423
#define S9                              1423
#define IDC_AXIS_POS_EDIT_X             1500
#define IDC_AXIS_POS_EDIT_Y             1501
#define IDC_AXIS_POS_EDIT_Z             1502
#define IDC_AXIS_POS_EDIT_U             1503
#define IDC_AXIS_POS_EDIT_Z2            1503
#define IDC_AXIS_POS_EDIT_WEIGHT        1503
#define IDC_AXIS_POS_CHECK_DISPENSE_ONOFF 1504
#define IDC_AXIS_POS_EDIT_WAIT_TIME     1505
#define IDC_AXIS_POS_COMBO_CMD_TYPE     1506
#define IDC_AXIS_POS_EDIT_VEL           1507
#define IDC_AXIS_POS_CHECK_VEL          1508
#define IDC_AXIS_POS_CHECK_DELAY        1509
#define IDC_AXIS_POS_CHECK_ANGLE        1510
#define IDC_AXIS_POS_EDIT_ANGLERADIUS   1511
#define IDC_AXIS_POS_RADIO_HEAD         1514
#define IDC_ZHEIGHT_EDIT_B1             1519
#define IDC_ZHEIGHT_EDIT_M1             1520
#define IDC_ZHEIGHT_EDIT_T2             1521
#define ID_CMD_MARK                     1790
#define ID_CMD_BRUSHAREA                1791
#define ID_CMD_BATH                     1792
#define ID_CMD_TOOL                     1793
#define ID_CMD_ZHEIGHT                  1794
#define ID_CMD_STEPX_ZH                 1795
#define ID_CMD_STEPY_ZH                 1796
#define ID_CMD_OMRON                    1797
#define ID_CMD_DISPENSER                1801
#define ID_CMD_GOTOADDRESS              1802
#define ID_CMD_STEPX                    1803
#define ID_CMD_STEPY                    1804
#define ID_CMD_CALLSUBROUTINUE          1806
#define ID_CMD_LABEL                    1807
#define ID_CMD_NULL_LINE                1808
#define ID_CMD_SETIO                    1809
#define ID_CMD_WAITPOINT                1810
#define ID_CMD_STOPPOINT                1811
#define ID_CMD_HOME                     1812
#define ID_CMD_LOOP                     1813
#define ID_CMD_NOTE                     1814
#define ID_CMD_DUMMY                    1815
#define ID_CMD_END_PROGRAM              1816
#define ID_CMD_SET_Z_SAME               1817
#define ID_CMD_DELAY                    1818
#define ID_CMD_CLEAR_ALL                1819
#define ID_CMD_DELETE                   1820
#define ID_CMD_REOPEN_FILE              1821
#define ID_CMD_COPY                     1822
#define ID_CMD_CUT                      1823
#define ID_CMD_PASTE                    1824
#define ID_PARAM_LINESPEED              1830
#define ID_PARAM_LINEEND                1831
#define ID_PARAM_POINTSETUP             1832
#define ID_PARAM_LINESETUP              1833
#define ID_PARAM_POINTEND               1834
#define ID_PARAM_Z_CLEARANCE            1835
#define ID_PARAM_ZLIMITHIGH             1836
#define ID_PARAM_VELXY                  1837
#define ID_PARAM_VELZ                   1838
#define ID_PARAM_Z_SET_HEIGHT           1839
#define ID_PARAM_JETSETUP               1840
#define ID_PARAM_HOME                   1845
#define IDC_SYNC_CONFIG_OPEN            1846
#define IDC_IO_OUT_OPEN                 1851
#define IDC_IO_OUT_CLOSE                1852
#define IDC_STANDBY_CMD_TYPE            1854
#define IDC_STANDBY_EDIT_X              1855
#define IDC_STANDBY_EDIT_Y              1856
#define IDC_STANDBY_EDIT_Z              1857
#define IDC_STANDBY_EDIT_U              1858
#define IDC_GOSUB_RADIO1                1859
#define IDC_GOSUB_RADIO2                1860
#define IDC_GOSUB_EDIT_START_CMD        1861
#define IDC_GOSUB_STATIC_NO             1862
#define IDC_GOSUB_STATIC_LAB            1863
#define IDC_ZHEIGHT_EDIT_X              1870
#define IDC_ZHEIGHT_EDIT_Y              1871
#define IDC_ZHEIGHT_EDIT_Z              1872
#define IDC_ZHEIGHT_READ_AXISPOS        1873
#define IDC_ZHEIGHT_MOVE                1874
#define IDC_DLG_JET_ADJUST_NUM          1880
#define IDC_DLG_JET_ADJUST_LIST         1881
#define IDC_DLG_JET_ADJUST_START        1882
#define IDC_DLG_JET_ADJUST_END          1883
#define IDC_DLG_JET_ADJUST_PROGRESS1    1884
#define IDC_DLG_JET_ADJUST_EX           1885
#define IDC_DLG_JET_ADJUST_OPEN_TIME    1885
#define IDC_DLG_JET_ADJUST_NUM3         1886
#define IDC_DLG_JET_ADJUST_UP_HEIGHT    1886
#define IDC_CIRCLE_EDIT_OVERANGLE       1890
#define IDC_PAGE_IMG_EXPOSURE_TIME      1892
#define IDC_PAGE_JET_EDIT_PULSE         1893
#define IDC_PAGE_IMG_GAIN               1894
#define IDC_PAGE_JET_EDIT_ONTIME        1895
#define IDC_DLG_JET_ADJUST_RX           1896
#define IDC_DLG_JET_ADJUST_RY           1897
#define IDC_DLG_JET_ADJUST_EY           1898
#define IDC_DLG_JET_ADJUST_EZ           1899
#define IDC_PAGE_JET_EDIT_OFFTIME       1900
#define IDC_DLG_JET_ADJUST_EY2          1900
#define IDC_DLG_JET_ADJUST_EZ2          1900
#define IDC_PAGE_JET_EDIT_PRESS1        1901
#define IDC_PAGE_JET_EDIT_PRESS2        1902
#define IDC_PAGE_JET_EDIT_TP            1903
#define IDC_PAGE_JET_EDIT_PRESS3        1903
#define IDC_PAGE_JET_STATIC_TP          1904
#define IDC_PAGE_APP_RADISP1            1905
#define IDC_PAGE_APP_RADISP3            1907
#define IDC_PAGE_APP_RADIST1            1908
#define IDC_PAGE_APP_RADISIDC_PAGE_APP_RADIST2 1909
#define IDC_PAGE_APP_RADIST2            1909
#define IDC_PAGE_APP_RADIST_WORKMODE1   1910
#define IDC_PAGE_APP_RADIST4            1911
#define IDC_PAGE_APP_RADIST_WORKMODE2   1911
#define IDC_DLG_NEEDLE_ZH_LED           1912
#define IDC_PAGE_APP_RADISP4            1912
#define IDC_PAGE_APP_RADISP2            1912
#define IDC_DLG_NEEDLE_ADJUST_DISP      1913
#define IDC_USERTYPE                    1914
#define IDC_DLG_INFO_MODE               1919
#define IDC_DLG_JET_ADJUST_OFFX         1920
#define IDC_DLG_JET_ADJUST_OFFY         1921
#define IDC_DLG_JET_ADJUST_JOG          1922
#define IDC_USER_LOGOFF                 1923
#define IDC_PAGE_IMG_R1                 1924
#define IDC_PAGE_IMG_R2                 1925
#define IDC_PAGE_SYS_SEARCH_NUM         1928
#define IDC_PAGE_SYS_XY_DIST            1929
#define IDC_PAGE_APP_WASH_COUNT         1930
#define IDC_PAGE_IMG_ZHEIGHT            1931
#define IDC_PAGE_APP_WASH_COUNT2        1931
#define IDC_PAGE_APP_WASH_TIMER         1931
#define IDC_PAGE_IMG_LEARN              1932
#define IDC_PAGE_APP_WEGHT_MAXLMT       1932
#define IDC_PAGE_IMG_SAVE               1933
#define IDC_PAGE_APP_TEST_OTIMER        1933
#define IDC_PAGE_APP_WEGHT_MINLMT       1933
#define IDC_SHOTCUT_JOG_XY_SPEED        1934
#define IDC_SHOTCUT_JOG_Z_SPEED         1935
#define IDC_JOG_BUTTON_EXT              1936
#define IDC_DLG_NEEDLE_ADJUST_JOG       1937
#define IDC_DLG_NEEDLE_ADJUST_OFFX      1938
#define IDC_DLG_NEEDLE_ADJUST_OFFY      1939
#define IDC_DLG_NEEDLE_ZH_STATIC        1940
#define IDC_DLG_TOOL_RADIO_HEAD         1941
#define IDC_DLG_TOOL_PULSE_NUM          1942
#define IDC_DLG_TOOL_OPEN_TIME          1943
#define IDC_DLG_TOOL_CLOSE_TIME         1944
#define IDC_BUTTON_PAT_SAVE             1945
#define IDC_DLG_TOOL_Z_HEIGHT           1945
#define IDC_JET_PARAM_PULSE_NUM         1946
#define IDC_DLG_TOOL_CLOSE_TIME2        1946
#define IDC_WCL_WPERPOINT               1946
#define IDC_EDIT_REGISTER_NEW_CODE      1946
#define IDC_DLG_TOOL_Z_HEIGHT2          1946
#define IDC_MARK_STATIC_PIXEL_RATE      1947
#define IDC_DLG_TOOL_CLOSE_TIME3        1947
#define IDC_WCL_LINEEIGHT               1947
#define IDC_DLG_TOOL_Z_HEIGHT3          1947
#define IDC_EDIT_REGISTER_DELAY         1947
#define IDC_MARK_STATIC_PIXEL_ANG       1948
#define IDC_WCL_LINEEIGHT2              1948
#define IDC_WCL_LINESPEED               1948
#define IDC_DLG_PIXEL_EDIT_ACCEPTANCE   1949
#define IDC_DLG_PIXEL_BTN_LEARN         1950
#define IDC_DLG_PIXEL_EDIT_X            1951
#define IDC_DLG_PIXEL_EDIT_Y            1952
#define IDC_DLG_PIXEL_EDIT_Z            1953
#define IDC_DLG_PIXEL_BTN_MOVE          1954
#define IDC_DLG_PIXEL_BTN_PAT_TEST      1955
#define IDC_DLG_PIXEL_BTN_PAT_SAVE      1956
#define IDC_EDIT_ZSET                   1957
#define IDC_PAGE_IMG_CHECK_YDIR         1958
#define IDC_PAGE_IMG_CHECK_XDIR         1959
#define IDC_REPEAT_ZHEIGHT_EDIT_TYPE    1959
#define IDC_REPEAT_ZHEIGHT_RADIO1       1960
#define IDC_REPEAT_ZHEIGHT_RADIO2       1961
#define IDC_REPEAT_ZHEIGHT_EDIT_XNUM    1962
#define IDC_REPEAT_ZHEIGHT_EDIT_YNUM    1963
#define IDC_REPEAT_ZHEIGHT_EDIT_XSPACE  1964
#define IDC_REPEAT_ZHEIGHT_EDIT_YSPACE  1965
#define IDC_REPEAT_ZHEIGHT_EDIT_X       1966
#define IDC_REPEAT_ZHEIGHT_EDIT_Y       1967
#define IDC_REPEAT_ZHEIGHT_EDIT_Z       1968
#define IDC_REPEAT_ZHEIGHT_EDIT_B1      1969
#define IDC_REPEAT_ZHEIGHT_EDIT_M1      1970
#define IDC_REPEAT_ZHEIGHT_EDIT_T2      1971
#define IDC_REPEAT_ZHEIGHT_SAVE         1972
#define IDC_REPEAT_ZHEIGHT_APPLY        1973
#define IDC_REPEAT_ZHEIGHT_MOVE         1974
#define IDC_REPEAT_ZHEIGHT_READ_AXISPOS 1975
#define IDC_INFO_CHECK_BYPASS           1976
#define IDC_INFO_CHECK_BYPASS2          1977
#define IDC_INFO_CHECK_ENABLFEED        1977
#define IDC_INFO_CHECK_ENABLEAPFS       1977
#define IDC_COMBO1                      1985
#define IDC_COMBO_MARKNUM               1985
#define IDC_COMBO_DISP_SEL              1985
#define IDC_COMBO_DISP_SEL2             1986
#define IDC_COMBO_DISP_TYPE             1986
#define IDC_COMBO_DISP_TYPE2            1987
#define IDC_COMBO_DISP_CTRL             1987
#define IDC_EDIT_UNFEEDCHIPDIS          1988
#define IDC_SET_JOGXYZ_WP               2028
#define IDC_SET_JOGXYZ_WN               2029
#define IDC_SET_JOGXYZ_NN               2030
#define IDC_SET_JOGXYZ_NP               2031
#define IDC_BUTTON_UNFEEDPHSH           2032
#define IDC_SET_JOGXYZ_EDITV            2032
#define IDC_SET_JOGXYZ_EDITW            2033
#define IDC_SET_JOGXYZ_EDITM            2034
#define IDC_SET_JOGXYZ_EDITN            2035
#define IDC_SET_JOGXYZ_MP               2036
#define IDC_SET_JOGXYZ_MN               2037
#define IDC_SET_JOGXYZ_SLIDER_SPEED1    2038
#define IDC_SET_JOGXYZ_EDIT_SPEED1      2039
#define IDC_PROGRESS_FEEDCURID          2041
#define IDC_PROGRESS_UNFEEDCURID        2042
#define IDC_BUTTON_FEEDREADY            2045
#define IDC_BUTTON_FEEDREADY2           2046
#define IDC_BUTTON5                     2057
#define IDC_BUTTON1                     2057
#define IDC_BUTTON_CLOSEPRESS           2057
#define IDC_BTN_WT_ADJ                  2057
#define IDC_BTN_TRACK_L                 2057
#define IDC_BT_BANLENCE_ZERO            2058
#define IDC_BUTTON_CLOSEPRESS2          2058
#define IDC_BUTTON_OPENPRESS            2058
#define IDC_STATIC_FREADY               2058
#define IDC_BUTTON2                     2058
#define IDC_REGISTER_DELAY              2058
#define IDC_UPDATE_DATEDELAY            2058
#define IDC_BTN_LINK                    2058
#define IDC_BTN_LOAD_FROM_FILE          2058
#define IDC_BTN_MOVTO_JET_TEST_POS      2058
#define IDC_BTN_CCD_TRIGGER             2058
#define IDC_BTN_ADD                     2058
#define IDC_BTN_STOP_11                 2058
#define IDC_BTN_SET                     2058
#define IDC_BTN_MOV_1                   2058
#define IDC_BTN_SET_BD1                 2058
#define IDC_BTN_Move_Rotate_1           2058
#define IDC_STATIC_UFREADY              2059
#define IDC_BUTTON3                     2059
#define IDC_STATIC_BCDATA2              2059
#define IDC_BTN_SET_PARAM               2059
#define IDC_BTN_SET_JET_TEST_POS        2059
#define IDC_BTN_LOAD_IMAGE              2059
#define IDC_BTN_SAVE_LIGHT              2059
#define IDC_BTN_DEL                     2059
#define IDC_BTN_STOP_12                 2059
#define IDC_BTN_SAVE                    2059
#define IDC_BTN_MOV_2                   2059
#define IDC_BTN_Teach_Rotate_2          2059
#define IDC_EDIT_OPENDISPTIME2          2060
#define IDC_COMBO_BMARK                 2060
#define IDC_BUTTON_OPENPRESS2           2060
#define IDC_BUTTON_OPENHREAT            2060
#define IDC_BT_BC_GETDATA2              2060
#define IDC_BTN_MOVTO_JET_TEST_POS2     2060
#define IDC_BTN_CONTACT_TEST            2060
#define IDC_BTN_CLAMP                   2060
#define IDC_BTN_MACHINE_SET             2060
#define IDC_BTN_PAUSE                   2060
#define IDC_BTN_MOV_3                   2060
#define IDC_BTN_MOV_BD2                 2060
#define IDC_BTN_Move_Rotate_2           2060
#define IDC_BTN_PARAM                   2060
#define IDC_BTN_BMOVE                   2061
#define IDC_BT_BANLENCE_ZERO2           2061
#define IDC_BTN_SET_ZSAFE_POS           2061
#define IDC_BTN_LIFT_2                  2061
#define IDC_BTN_LIFT                    2061
#define IDC_BTN_CONTACT_TEST2           2061
#define IDC_BTN_READ_LASER              2061
#define IDC_BTN_JETADJUST               2061
#define IDC_BUTTON8                     2061
#define IDC_BTN_STOP                    2061
#define IDC_BTN_SET_BD2                 2061
#define IDC_BTN_Move_Valve_1            2061
#define IDC_BUTTON_BLEARN               2062
#define IDC_BT_BC_GETDATA3              2062
#define IDC_BUTTON9                     2062
#define IDC_BTN_TARCK_R                 2062
#define IDC_BTN_MOVTO_LASER_BASE_POS    2062
#define IDC_BTN_USER                    2062
#define IDC_BTN_PAUSE2                  2062
#define IDC_Btn_Load_Board              2062
#define IDC_BUTTON_PAT_BTEST            2063
#define IDC_BUTTON4                     2063
#define IDC_BTN_SET_JET_TEST_POS2       2063
#define IDC_BTN_SET_LASER_BASE_POS      2063
#define IDC_BTN_TRACK_L2                2063
#define IDC_BUTTON_PAT_BSAVE            2064
#define IDC_BUTTON6                     2064
#define IDC_BTN_CONTACT_READ_HEIGHT     2064
#define IDC_BTN_TARCK_R2                2064
#define IDC_MARK_EDIT_BACCEPTANCE       2065
#define IDC_BTN_READ_PRESSURE           2065
#define IDC_BTN_UNFIX                   2065
#define IDC_MARK_EDIT_BX                2066
#define IDC_BTN_SET_PRESSURE            2066
#define IDC_BTN_UNLOAD                  2066
#define IDC_MARK_EDIT_BY                2067
#define IDC_MARK_EDIT_BZ                2068
#define IDC_STATIC_MARK_BPAT            2069
#define S_1                             2070
#define S2                              2071
#define S4                              2072
#define S6                              2073
#define S_2                             2074
#define S_3                             2075
#define S_4                             2076
#define S_5                             2077
#define S_6                             2078
#define S_7                             2079
#define S_8                             2080
#define S_9                             2081
#define S_10                            2082
#define S_11                            2083
#define S11                             2083
#define S_12                            2084
#define Tag_1                           2090
#define Tag_2                           2091
#define Tag_3                           2092
#define Tag_4                           2093
#define Tag_5                           2094
#define Tag_6                           2095
#define Tag_7                           2096
#define Tag_8                           2097
#define Tag_9                           2098
#define Tag_10                          2099
#define Tag_11                          2100
#define Tag_12                          2101
#define Tag_13                          2102
#define Tag_14                          2103
#define Tag_15                          2104
#define Tag_16                          2105
#define Tag_17                          2106
#define Tag_18                          2107
#define Tag_19                          2108
#define Tag_20                          2109
#define Tag_21                          2110
#define Tag_22                          2111
#define Tab_1                           2112
#define Tag_23                          2112
#define Tab_2                           2113
#define Tab_3                           2114
#define Tag_24                          2114
#define Tag_1222                        2115
#define Tag_1223                        2116
#define Btn_1                           2117
#define Tag_1224                        2117
#define Btn_2                           2118
#define Btn_3                           2119
#define IDC_WLPOSX                      2120
#define IDC_WLPOSY                      2121
#define IDC_WLPOSZ                      2122
#define IDC_DLG_WL_POINTNUM             2123
#define IDC_WL_DISPDROPDATE             2124
#define IDC_WL_DISPMG                   2125
#define IDC_DLG_COMB_POS                2126
#define IDC_WCL_POSX                    2127
#define IDC_WCL_POSY                    2128
#define IDC_WCL_POSZ                    2129
#define IDC_WCL_LINEPOINTNUM            2130
#define IDC_WCL_LINEPOINTNUM2           2131
#define IDC_WCR_POSX                    2131
#define IDC_WCR_POSY                    2132
#define IDC_WCR_POSZ                    2133
#define IDC_DLG_COMB_WCRPOS             2134
#define IDC_WCR_POINTNUM                2135
#define IDC_CHECK1                      2136
#define IDC_CHECK_GOSTANDBYPOS          2136
#define IDC_EDIT_REGISTER_CODE          2137
#define IDC_CHECK_FILESAPTER            2137
#define IDC_CHECK_GOSTANDBYPOS2         2137
#define IDC_CHK_REV_STOP_2              2137
#define IDC_BTN_REGISTER_MODIFY         2138
#define IDC_UPDATE_PASSWORD             2138
#define IDC_EDIT_REGISTER_DEVICEID      2138
#define IDC_CHECK_ENABLEWORKTEGETHER    2138
#define IDC_CHK_REV_CLAMP               2138
#define IDC_EDIT_DELAYDATE              2139
#define IDC_CHECK_ENABLEWORKTEGETHER2   2139
#define IDC_CHECK_ENABLESQERTEANLE      2139
#define IDC_BUTTON_UPDATE_PID           2140
#define IDC_PAGE_JET_EDIT_PUSLEWIDTH2   2147
#define ID_BT_REGESITSOFT               2147
#define IDC_EDIT_PASSWORDTYPE           2148
#define IDC_EDIT_LIFESPAN               2149
#define IDC_EDIT_LIFESPAN_NOUSERED      2150
#define IDC_SET_LINE_YN                 2150
#define IDC_SET_LINEYP                  2151
#define IDC_SET_LINE_YP                 2151
#define IDC_SET_LINE_XP                 2152
#define IDC_SET_LINE_XN                 2153
#define IDC_STATIC_KP                   2154
#define IDC_STATIC_KI                   2155
#define IDC_STATIC_KD                   2156
#define IDC_STATIC_KVFF                 2157
#define IDC_STATIC_KAFF                 2158
#define IDC_STATIC_SPEEDLOAD            2159
#define IDC_EDIT1                       2160
#define IDC_EDIT_STEPNUM                2160
#define IDC_EDIT_FLYJETDELAY            2160
#define IDC_EDIT_WT_COMSTR              2160
#define IDC_EDIT_WTPOS_X                2160
#define IDC_EDIT_JET_TEST_X             2160
#define IDC_EDIT_CUR_PROG               2160
#define IDC_EDIT_DISP_HEIGHT            2160
#define IDC_EDIT_MODIFY                 2160
#define IDC_EDIT_DOT_D                  2160
#define IDC_EDIT_CLEAN_INTERVAL         2160
#define IDC_EDIT_LTX                    2160
#define IDC_EDIT_OPEN_DOTNUM            2160
#define IDC_EDIT_Rotate_Mark_x1         2160
#define IDC_AXIS_HPOS_EDIT_X            2161
#define IDC_EDIT_                       2161
#define IDC_EDIT_MAKEUPNUM              2161
#define IDC_EDIT_WT_WEIGHT              2161
#define IDC_EDIT_WTPOS_Y                2161
#define IDC_EDIT2                       2161
#define IDC_EDITJET_TEST_Y              2161
#define IDC_EDIT_JET_TEST_Y             2161
#define IDC_EDIT_CUR_PROG2              2161
#define IDC_EDIT_ADD_PROG               2161
#define IDC_EDIT_AUTO_RPS_INV           2161
#define IDC_EDIT_CLEAN_INTERVAL2        2161
#define IDC_EDIT_CLEAN_NUM              2161
#define IDC_EDIT_LTY                    2161
#define IDC_EDIT_Rotate_Mark_y1         2161
#define IDC_AXIS_HPOS_EDIT_Y            2162
#define IDC_EDIT_MAKEUPNUM2             2162
#define IDC_EDIT_AUTORPSDELAY           2162
#define IDC_EDIT_LA_COMSTR              2162
#define IDC_EDIT_WTPOS_X2               2162
#define IDC_EDITJET_TEST_Y2             2162
#define IDC_EDIT_Z_SAFE_POS             2162
#define IDC_EDIT_WT_Z_POS               2162
#define IDC_EDIT_WTPOS_Z                2162
#define IDC_EDIT_ADD_PROG_DISCRIPTIO    2162
#define IDC_EDIT_ADD_PROG_DISCRIPTION   2162
#define IDC_EDIT_AUTO_RPS_DOTS          2162
#define IDC_EDIT_CLEAN_DOWN_MM          2162
#define IDC_EDIT5                       2162
#define IDC_EDIT_RTX                    2162
#define IDC_EDIT_Rotate_Mark_x2         2162
#define IDC_AXIS_HPOS_EDIT_Z            2163
#define IDC_EDIT_AUTORPSDELAY2          2163
#define IDC_EDIT_AUTORPSTIMES           2163
#define IDC_EDIT_LA_HEIGHT              2163
#define IDC_EDIT_WTPOS_Y2               2163
#define IDC_EDIT_WT_NUM                 2163
#define IDC_EDIT_JET_TEST_Y2            2163
#define IDC_EDIT_JET_TEST_Z             2163
#define IDC_EDIT_DOT_D2                 2163
#define IDC_EDIT_CLEAN_INV              2163
#define IDC_EDIT6                       2163
#define IDC_EDIT_RTY                    2163
#define IDC_EDIT_Rotate_Mark_y2         2163
#define IDC_AXIS_HPOS_EDIT_X2           2164
#define IDC_BUTTON_HANDSELIMT           2164
#define IDC_EDIT_AUTOSRPSTIME           2164
#define IDC_EDIT_DEF_GLUE_WT            2164
#define IDC_AXIS_HPOS_EDIT_WEIGHT       2164
#define IDC_EDIT_JET_TEST_X2            2164
#define IDC_AXIS_HPOS_EDIT_PREDOT       2164
#define IDC_EDIT_AUTO_RPS_INV2          2164
#define IDC_EDIT7                       2164
#define IDC_EDIT_RBX                    2164
#define IDC_EDIT_Valve_x1               2164
#define IDC_AXIS_HPOS_EDIT_Y2           2165
#define IDC_BUTTON_HANDSELIMT2          2165
#define IDC_EDIT_AUTOSRPSDELAY          2165
#define IDC_EDIT_DEF_GLUE_WT2           2165
#define IDC_EDIT_JET_TEST_Y3            2165
#define IDC_AXIS_HPOS_EDIT_WEIGHT2      2165
#define IDC_AXIS_HPOS_END_PREDOT        2165
#define IDC_EDIT_AUTO_RPS_DOTS2         2165
#define IDC_EDIT8                       2165
#define IDC_EDIT_RBY                    2165
#define IDC_EDIT_Valve_y1               2165
#define IDC_BUTTON_HANDSELIMT3          2166
#define IDC_BUTTON_ARCMARK              2166
#define IDC_AXIS_HPOS_EDIT_Z2           2166
#define IDC_EDIT_JET_TEST_Z2            2166
#define IDC_EDIT_PROBE_H_SPD            2166
#define IDC_EDIT_Valve_Space            2166
#define IDC_BUTTON_HANDSELIMT4          2167
#define IDC_FEED_FEED_UPVEL             2167
#define IDC_EDIT_PROBE_L_SPD            2167
#define IDC_EDIT_Needle_Rad             2167
#define IDC_DLG_FEEDCTRL_FEEDUP         2168
#define IDC_BUTTON_HANDSELIMT5          2168
#define IDC_EDIT_CLEAN_NUM2             2168
#define IDC_EDIT_PROBE_L_HEIGHT         2168
#define IDC_EDIT_Valve_z1               2168
#define IDC_DLG_FEEDCTRL_FEEDDOWN       2169
#define IDC_BUTTON_HANDSELIMT6          2169
#define IDC_DLG_FEEDCTRL_UNFEEDUP       2170
#define IDC_DLG_FEEDCTRL_UNFEEDDOWN     2171
#define IDC_DLG_FEEDCTRL_VELSET         2172
#define IDC_FEED_FEED_DOWNVEL           2173
#define IDC_DLG_BASESET_SETBASE         2174
#define IDC_BASE_BASEDATE               2175
#define IDC_BASE_JETHIGHT               2176
#define IDC_STATIC_BCDATA               2177
#define IDC_LIST_DATATOTOL              2178
#define IDC_DLG_MTR_GRID                2180
#define ID_SAVE                         2181
#define IDC_COM_GRID                    2182
#define IDC_BTN_CLOSE                   2183
#define IDC_BTN_WT_SET0                 2184
#define IDC_BTN_WT_READ                 2185
#define IDC_BTN_LOAD_FROM_DISP          2185
#define IDC_EDIT_PRESSURE               2186
#define IDC_BTN_LA_READ                 2187
#define IDC_BTN_MVTO_WTPOS              2187
#define IDC_BTN_SET_WTPOS               2188
#define IDC_BTN_SET_WTPOS2              2189
#define IDC_EDIT_RISINGTIME             2190
#define IDC_EDIT_OPEN                   2192
#define IDC_EDIT_LIFT                   2194
#define IDC_EDIT_DOWN                   2196
#define IDC_EDIT_DELAY                  2198
#define IDC_EDIT_PULSE                  2200
#define IDC_EDIT_TEMP                   2201
#define IDC_SCR_RISING                  2202
#define IDC_SCR_OPEN                    2203
#define IDC_SCR_LIFT                    2204
#define IDC_SCR_DOWN                    2205
#define IDC_SCR_DELAY                   2206
#define IDC_SCR_PUL                     2207
#define IDC_SCR_TEMP                    2208
#define IDC_BTN_VALVE_ON                2212
#define IDC_STATIC1                     2213
#define IDC_STATIC2                     2214
#define IDC_STATIC3                     2215
#define IDC_STATIC4                     2216
#define IDC_STATIC11                    2217
#define IDC_STATIC13                    2218
#define IDC_STATIC14                    2219
#define IDC_EDIT_LIGHT                  2221
#define IDC_SCROLLBAR1                  2222
#define IDC_SCR_LIGHT                   2222
#define IDC_BTN_SEL                     2223
#define IDC_PROG_LIST                   2224
#define IDC_STATIC_1                    2225
#define IDC_STATIC_2                    2226
#define IDC_BTN_ASK_PRE                 2227
#define IDC_BTN_ASK_NEXT                2228
#define IDC_STATIC_3                    2229
#define IDC_STATIC_4                    2230
#define IDC_STATIC_5                    2231
#define IDC_STATIC_6                    2232
#define IDC_STATIC_7                    2233
#define IDC_STATIC_8                    2234
#define IDC_STATIC_9                    2235
#define IDC_STATIC_10                   2236
#define IDC_STATIC_11                   2237
#define IDC_BTN_LOAD                    2238
#define IDC_BTN_FIX                     2239
#define IDC_STATIC_12                   2240
#define IDC_STATIC_13                   2241
#define IDC_STATIC_14                   2242
#define IDC_STATIC_15                   2243
#define IDC_CHECK6                      2244
#define IDC_CHECK8                      2246
#define IDC_STATIC_16                   2246
#define IDC_RADIO1                      2247
#define IDC_RADIO2                      2248
#define IDC_EDIT_BASE_CONTACT_HEIGHT    2248
#define IDC_RADIO3                      2249
#define IDC_EDIT_BASE_LASER_HEIGHT      2249
#define IDC_RADIO4                      2250
#define IDC_RADIO5                      2251
#define IDC_RADIO6                      2252
#define IDC_BTN_REV_BOARD               2253
#define IDC_BTN_WORK2REV                2254
#define IDC_CHK_REV_STOP_1              2255
#define IDC_BTN_REV2WORK                2256
#define IDC_BTN_WASTEGLUE__CLEAR        2256
#define IDC_BTN_REV_BOARD2              2257
#define IDC_BTN_REV_HOME                2257
#define IDC_CHECK2                      2257
#define IDC_CHK_WEIGHT                  2257
#define IDC_STATIC_17                   2258
#define IDC_BUTTON_EDIT_DOT             2258
#define IDC_STATIC_18                   2259
#define IDC_LIST_PATH                   2259
#define IDC_STATIC_19                   2260
#define IDC_BTN_SHOWPATH                2260
#define IDC_BTN_MOV                     2261
#define IDC_RADIO_T                     2262
#define IDC_RADIO_P                     2263
#define IDC_EDIT3                       2264
#define IDC_EDIT_TEST__LEN              2264
#define IDC_EDIT_UNIT_NUM               2264
#define IDC_EDIT_Z_CurPos               2264
#define IDC_EDIT4                       2265
#define IDC_EDIT_WEIGHT_INTERVAL_VALUE  2265
#define IDC_EDIT_TEST_SPACE             2265
#define IDC_EDIT_Z_Step                 2265
#define IDC_BUTTON_EDIT_SINGLE          2266
#define IDC_EDIT_TEST__LEN2             2266
#define IDC_EDIT_TEST__VEL              2266
#define IDC_BUTTON_EDIT_ALL             2267
#define IDC_GRID_POS                    2268
#define IDC_BTN_REVIEW_F                2268
#define IDC_BTN_MOVTO                   2269
#define IDC_BUTTON_EDIT_ALL3            2269
#define IDC_BTN_REVIEW_B                2269
#define ID_BTN_SAVE                     2270
#define IDC_BTN_PATH                    2274
#define IDC_LIST1                       2275
#define IDC_TAB1                        2276
#define IDC_BTN_RUN                     2277
#define IDC_RADIO_CAMERA_DALSA          2278
#define IDC_RADIO_CAMERA_HK             2279
#define IDC_RADIO_HEIGHT_LASER          2280
#define IDC_BTN_PROBE_SWITCH            2280
#define IDC_RADIO_HEIGHT_PROBE          2281
#define IDC_RADIO_LDULD_ONLINE          2282
#define IDC_RADIO_HEIGHT_PROBE2         2283
#define IDC_RADIO_LDULD_OFLINE          2283
#define IDC_RADIO_WORKMODE_JET          2284
#define IDC_RADIO_WORKMODE_NEEDLE       2285
#define IDC_RADIO_WORKMODE_CAMERA       2286
#define IDC_BTN_CLEAN                   2287
#define IDC_CHECK_AUTO_CLEAN            2288
#define IDC_BTN_HOME                    2289
#define IDC_CHECK_AUTO_CLEAN2           2289
#define IDC_CHECK_AUTO_RPS              2289
#define IDC_CHK_GLUE_WARNING            2290
#define IDC_BTN_SET_1                   2291
#define IDC_BTN_SET_2                   2292
#define IDC_CHECK_IF_TESTGLUE           2292
#define IDC_BTN_SET_3                   2293
#define IDC_BTN_MOV_BD1                 2293
#define IDC_BTN_TEST                    2294
#define IDC_BTN_POS_CLEAN               2295
#define IDC_RADIO_GLUE_SNR              2296
#define IDC_RADIO_GLUE_PCS              2297
#define IDC_EDIT9                       2298
#define IDC_EDIT_GLUE_PCS               2298
#define IDC_BTN_NEW_GLUE                2299
#define IDC_RADIO_GLUE_PCS2             2300
#define IDC_EDIT10                      2301
#define IDC_EDIT_GLUE_MINUTE            2301
#define IDC_BTN_NEW_GLUE2               2302
#define IDC_CHECK_SAFEDOOR              2302
#define IDC_CHECK_Camera_Needle         2303
#define IDC_CHECK_Workpiece_Rotate      2304
#define IDC_RADIO_VALVE_1               2305
#define IDC_RADIO_VALVE_2_SYS           2306
#define IDC_STATIC_Image                2307
#define IDC_BTN_Teach_Rotate_1          2308
#define IDC_STATIC_PARAM_DOT            2308
#define IDC_BTN_Rotate                  2309
#define IDC_BTN_Teach_Valve_1           2310
#define IDC_BTN_MultiValve_Set          2310
#define IDC_BTN_Move_Valve_2            2311
#define IDC_CHECK_CONVeyor              2311
#define IDC_STATIC_ToolDetection        2312
#define IDC_BTN_ZUp                     2313
#define IDC_BTN_ZDown                   2314
#define IDC_STATIC_PROGNAME             2314
#define IDC_BTN_Move_Valve_TD1          2315
#define IDC_LIST2                       2315
#define IDC_BTN_Move_Valve_TD2          2316
#define IDC_DLG_PARAM_DOT_GRID          2403
#define IDC_DLG_PARAM_LINE_GRID         2404
#define IDC_COMBO_MODIFY                2405
#define IDC_BTN_PARAM_DOT_SAVE          2406
#define IDC_BTN_PARAM_LINE_SAVE         2407
#define IDC_Btn_Unload_Board            2408
#define IDC_SET_HEIGHT_COMBO_ID         2812
#define IDC_DLG_NEEDLE_ZH_EDIT_Z        2818
#define IDC_DLG_NEEDLE_ZH_EDIT_X        2819
#define IDC_DLG_NEEDLE_ZH_EDIT_Y        2820
#define IDC_DLG_NEEDLE_ZH_CALI          2822
#define IDC_DLG_NEEDLE_ZH_OFFSET        2823
#define IDC_DLG_NEEDLE_ZH_EDIT_STD      2825
#define IDC_DLG_NEEDLE_ZH_EDIT_DELTA    2826
#define IDC_SET_JOGXYZ_XN               2900
#define IDC_SET_JOGXYZ_XP               2901
#define IDC_SET_JOGXYZ_YN               2902
#define IDC_SET_JOGXYZ_YP               2903
#define IDC_SET_JOGXYZ_ZN               2904
#define IDC_SET_JOGXYZ_ZP               2905
#define IDC_SET_JOGXYZ_CHECK_STEP       2906
#define IDC_SET_JOGXYZ_EDIT_STEP        2907
#define IDC_SET_JOGXYZ_SLIDER_SPEED     2908
#define IDC_SET_JOGXYZ_EDIT_SPEED       2909
#define IDC_SET_JOGXYZ_VN               2910
#define IDC_SET_JOGXYZ_VP               2911
#define IDC_PAGE_POS_WASH_SAVE          3111
#define IDC_PAGE_POS_WASH_MOVETO        3112
#define IDC_PAGE_POS_HOME_SAVE          3113
#define IDC_PAGE_POS_HOME_MOVETO        3114
#define IDC_PAGE_POS_ZADJUST_SAVE       3115
#define IDC_PAGE_POS_ZADJUST_MOVETO     3116
#define IDC_PAGE_POS_WASH_X             3117
#define IDC_PAGE_POS_WASH_Y             3118
#define IDC_PAGE_POS_WASH_Z             3119
#define IDC_PAGE_POS_HOME_X             3120
#define IDC_PAGE_POS_HOME_Y             3121
#define IDC_PAGE_POS_HOME_Z             3122
#define IDC_PAGE_POS_ZADJUST_X          3123
#define IDC_PAGE_POS_ZADJUST_Y          3124
#define IDC_PAGE_POS_ZADJUST_Z          3125
#define IDC_PAGE_POS_JET_SAVE           3126
#define IDC_PAGE_POS_JET_MOVETO         3127
#define IDC_PAGE_POS_JET_X              3128
#define IDC_PAGE_POS_JET_Y              3129
#define IDC_PAGE_POS_JET_Z              3130
#define IDC_PAGE_POS_NEEDLE_SAVE        3131
#define IDC_PAGE_POS_NEEDLE_MOVETO      3132
#define IDC_PAGE_POS_NEEDLE_X           3133
#define IDC_PAGE_POS_NEEDLE_Y           3134
#define IDC_PAGE_POS_NEEDLE_Z           3135
#define IDC_PAGE_POS_PIXEL_SAVE         3136
#define IDC_PAGE_POS_TESTJET_MOVETO     3136
#define IDC_PAGE_POS_PIXEL_MOVETO       3137
#define IDC_PAGE_POS_TESTJET_X          3137
#define IDC_PAGE_POS_PIXEL_X            3138
#define IDC_PAGE_POS_TESTJET_Y          3138
#define IDC_PAGE_POS_PIXEL_Y            3139
#define IDC_PAGE_POS_TESTJET_Z          3139
#define IDC_PAGE_POS_PIXEL_Z            3140
#define IDC_PAGTESTJET_SAVE             3140
#define IDC_PAGE_POS_JET_ZADJUST_SAVE   3141
#define IDC_PAGE_POS_JET_ZADJUST_MOVETO 3142
#define IDC_PAGE_POS_JET_ZADJUST_X      3143
#define IDC_PAGE_POS_JET_ZADJUST_Y      3144
#define IDC_PAGE_POS_JET_ZADJUST_Z      3145
#define IDC_PAGE_POS_AFPS_MOVETO        3146
#define IDC_PAGE_POS_AFPSX              3147
#define IDC_PAGE_POS_AFPSY              3148
#define IDC_PAGE_POS_AFPSZ              3149
#define IDC_PAGE_POS_AFPS_CALIB         3150
#define IDC_SET_JOGXYZ_EDITZ            3321
#define IDC_SET_JOGXYZ_EDITY            3322
#define IDC_SET_JOGXYZ_EDITX            3323
#define IDC_BTN_LOAD1                   4000
#define IDC_BTN_LBOX_U                  4001
#define IDC_BTN_LBOX_D                  4002
#define IDC_BTN_LMET_U                  4003
#define IDC_BTN_LMET_D                  4004
#define IDC_BTN_LOAD_OUT                4005
#define IDC_BTN_LOAD_BACK               4006
#define IDC_BTN_LU                      4007
#define IDC_BTN_LD                      4008
#define IDC_GRID_LD_POS                 4009
#define IDC_BTN_LMOV                    4010
#define IDC_BTN_LSET                    4011
#define IDC_BTN_UNLOAD1                 4012
#define IDC_BTN_ULBOX_U                 4013
#define IDC_BTN_ULBOX_D                 4014
#define IDC_BTN_ULMET_U                 4015
#define IDC_BTN_ULMET_D                 4016
#define IDC_BTN_UNLOAD_OUT              4017
#define IDC_BTN_UNLOAD_BACK             4018
#define IDC_COMBO2                      4019
#define IDC_BTN_ULU                     4020
#define IDC_BTN_ULD                     4021
#define IDC_GRID_ULD_POS                4022
#define IDC_BTN_ULMOV                   4023
#define IDC_BTN_ULSET                   4024
#define IDC_EDIT_LD_LAYERCOUNT          4025
#define IDC_EDIT_ULD_LAYERCOUNT         4026
#define ID_LOGON                        32801
#define ID_LOGOFF                       32802
#define ID_VIEW_CMD_EDIT                32803
#define ID_MENU_CMD_INSERT_TITLE_ITEM   32805
#define ID_MENU_CMD_TITLE_ITEM          32806
#define ID_MENU_CMD_PARAM_TITLE_ITEM    32807
#define ID_FILE_OPEN_DXF                32811
#define ID_ONLINE_ENABLE                32819
#define ID_RS232_CONFIG                 32820
#define ID_BUTTON32875                  32875
#define ID_Menu                         32879
#define ID_TOOLS_EDIT6                  32880
#define ID_BUTTON_EDIT7                 32882
#define IDS_TOOLS_BRECT                 32884
#define ID_CMDPOINT_WLRECT              32885
#define ID_CMDPOINT_WCRECT              32887
#define IDS_TOOLS_BRECT11               32888
#define ID_CMD_MARK1                    32889
#define ID_ABOUT                        32890
#define ID_CMD_SUPERSTART               32891
#define ID_CMD_SUPERPOINT               32892
#define ID_CMD_SUPEREND                 32893
#define ID_CMD_FILESEPARAT              32894
#define ID_CMD_FILESCRPEWORK            32895
#define IDS_TOOLS_SUPERSTART            32901
#define IDS_TOOLS_SUPERPOINT            32902
#define IDS_TOOLS_SUPEREND              32903
#define ID_CMD_BORATARC                 32904
#define ID_CMD_REV_BOARD                32913
#define ID_32914                        32914
#define ID_32915                        32915
#define ID_32916                        32916
#define ID_32917                        32917
#define ID_32918                        32918
#define ID_32919                        32919
#define ID_32920                        32920
#define ID_32921                        32921
#define ID_32922                        32922
#define ID_32923                        32923
#define ID_32924                        32924
#define ID_32925                        32925
#define ID_32926                        32926
#define ID_32927                        32927
#define ID_32928                        32928
#define ID_32929                        32929
#define ID_32930                        32930
#define ID_32931                        32931
#define ID_32932                        32932
#define ID_32933                        32933
#define ID_Menu32934                    32934
#define ID_32935                        32935
#define ID_32936                        32936
#define ID_32937                        32937
#define ID_32938                        32938
#define ID_32939                        32939
#define ID_32940                        32940
#define ID_32941                        32941
#define ID_32942                        32942
#define ID_32943                        32943
#define ID_32944                        32944
#define ID_32945                        32945
#define ID_32946                        32946
#define ID_32947                        32947
#define ID_Menu32948                    32948
#define ID_Menu32949                    32949
#define ID_32950                        32950
#define ID_32951                        32951
#define ID_CMD_LABEL_END                32952

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        458
#define _APS_NEXT_COMMAND_VALUE         32953
#define _APS_NEXT_CONTROL_VALUE         2409
#define _APS_NEXT_SYMED_VALUE           249
#endif
#endif
